Refactored and enhanced Nginx using new DSL.

diff --git a/nginx/templates/nginx.template b/nginx/templates/nginx.template
--- a/nginx/templates/nginx.template
+++ b/nginx/templates/nginx.template
@@ -9,44 +9,12 @@
 #   or used as /etc/init.d/nginx
 #
 
-action="${1:-""}"
-
-while [[ $# -gt 0 ]] ; do
-  token="$1" ; shift
-  case $token in
-    start|stop|restart|reload|log|shutdown|check|help)
-      action=$token
-      ;;
-    --confd) nginx_confd="$1"     ; shift ;;
-    --path)  nginx_path="$1"      ; shift ;;
-    --conf)  nginx_conf="$1"      ; shift ;;
-    --pid)   nginx_pid="$1"       ; shift ;;
-    --log)   nginx_log_path="$1"  ; shift ;;
-    --bin)   nginx="$1"           ; shift ;;
-    --lock)  nginx_lock="$1"      ; shift ;;
-    *)       action="error" ;;
-  esac
-done
-
-nginx_confd="${nginx_confd:-"/etc/conf.d/nginx"}"
-
-if [[ -s "$nginx_confd" ]] ; then
-  source "$nginx_confd"
-fi
-
-nginx_lock="${nginx_lock:-/var/lock/nginx}"
-if [[ -z "${nginx:-""}" ]] ; then
-  nginx="$(command -v nginx)"
-fi
-nginx="${nginx:-/sbin/nginx}"
-nginx_path="${nginx_path:-/etc/nginx}"
-nginx_conf="${nginx_conf:-"$nginx_path/nginx.conf"}"
-nginx_pid="${nginx_pid:-/var/run/nginx.pid}"
-nginx_log_path="${nginx_log_path:-/var/log/nginx}"
+log()  { printf "$*\n" ; return $? ;  }
+succeed() { log "$*" ; exit 0 ; }
+fail() { log "ERROR: $*" ; exit 1 ; }
 
 usage() {
-
-  printf "
+  log "
   Usage:
 
     $0 start stop restart reload log shutdown check help [options]
@@ -71,147 +39,173 @@ usage() {
     shutdown - Gracefully shut down workers
     check    - Check Nginx configuration for errors
     help     - Display this usage information
-
 "
 }
 
-start() {
+parse_args()
+{
+  while [[ $# -gt 0 ]] ; do
+    token="$1" ; shift
+    case $token in
+      start|stop|restart|reload|log|shutdown|check|status|help)
+        action=$token
+        ;;
+      --confd) nginx_confd="$1"     ; shift ;;
+      --path)  nginx_path="$1"      ; shift ;;
+      --conf)  nginx_conf="$1"      ; shift ;;
+      --pid)   nginx_pid="$1"       ; shift ;;
+      --log)   nginx_log_path="$1"  ; shift ;;
+      --bin)   nginx="$1"           ; shift ;;
+      --lock)  nginx_lock="$1"      ; shift ;;
+      *)       action="error" ;;
+    esac
+  done
+}
 
-  if [[ ${master_pid:-0} -gt 0 ]] ; then
+initialize()
+{
+  nginx_confd="${nginx_confd:-"/etc/conf.d/nginx"}"
 
-    printf "It appears that Nginx ($master_pid) is already running\n(from pidfile: $nginx_pid)\n"
+  if [[ -s "$nginx_confd" ]] ; then
+    source "$nginx_confd"
+  fi
 
+  nginx_lock="${nginx_lock:-/var/lock/nginx}"
+  if [[ -z "${nginx:-""}" ]] ; then
+    nginx="$(command -v nginx)"
+  fi
+  nginx="${nginx:-/sbin/nginx}"
+  nginx_path="${nginx_path:-/etc/nginx}"
+  nginx_conf="${nginx_conf:-"$nginx_path/nginx.conf"}"
+  nginx_pid="${nginx_pid:-/var/run/nginx.pid}"
+  nginx_log_path="${nginx_log_path:-/var/log/nginx}"
+
+  declare -i master_pid
+
+  if [[ -f "$nginx_pid" ]] ;then
+    master_pid=$(cat "$nginx_pid")
   else
+    master_pid=0
+  fi
+}
 
+nginx_start()
+{
+  if [[ ${master_pid:-0} -gt 0 ]] ; then
+    log "It appears that Nginx ($master_pid) is already running\n(from pidfile: $nginx_pid)"
+  else
     # TODO: Pass through the --pid and --log here.
     $nginx -c "$nginx_conf"
     result=$?
-
-    [[ $result -eq 0 ]] && touch $nginx_lock
-
+    if [[ $result -eq 0 ]] ; then
+      touch $nginx_lock
+    else
+      fail "Could not start Nginx server using config file ${nginx_conf}"
+    fi
   fi
-
 }
 
-stop() {
-
+nginx_stop()
+{
   if [[ ${master_pid:-0} -gt 0 ]] ; then
-
     kill -QUIT $master_pid
     result=$?
-
-    [[ $retval -eq 0 ]] && rm -f $nginx_lock
-
+    if [[ $retval -eq 0 ]] ; then
+      rm -f $nginx_lock
+    fi
   else
-
-    printf "It appears that Nginx is already not running\n(from pidfile: $nginx_pid)\n"
-
+    log "It appears that Nginx is already not running\n(from pidfile: $nginx_pid)"
   fi
-
 }
 
-restart() {
-
+nginx_restart()
+{
   if [[ ${master_pid:-0} -gt 0 ]] ; then
-
-    printf "Hot upgrading Nginx ($master_pid) running binary.\n"
-
+    log "Hot upgrading Nginx ($master_pid) running binary."
     kill -USR2 $master_pid
-
   else
-
-    printf "It appears that Nginx is not running.\n  (using pidfile: $nginx_pid)\nStarting Nginx.\n"
-
-    start
+    log "It appears that Nginx is not running.\n  (using pidfile: $nginx_pid)\nStarting Nginx."
+    nginx_start
   fi
 }
 
-reload() {
-
+nginx_reload()
+{
   if [[ ${master_pid:-0} -gt 0 ]] ; then
-
     printf "Reloading Nginx ($master_pid) configuration."
-
     kill -HUP $master_pid
-
   else
-
     printf "It appears that Nginx is not running.\n(from pidfile: $nginx_pid)\nStarting Nginx.\n"
-
-    start
+    nginx_start
   fi
 }
 
-log() {
-
+nginx_log()
+{
   if [[ ${master_pid:-0} -gt 0 ]] ; then
-
     printf "Re-opening Nginx ($master_pid) logs."
-
     kill -USR1 $master_pid
-
   else
-
     printf "It appears that Nginx is already not running\n(from pidfile: $nginx_pid)\nStarting Nginx.\n"
-
     start
   fi
-
 }
 
-
-shutdown() {
-
+nginx_shutdown()
+{
   if [[ ${master_pid:-0} -gt 0 ]] ; then
-
     printf "Gracefully shutting down Nginx ($master_pid) workers.\n  (workers will finish current request first)\n"
-
     kill -WINCH $master_pid
-
   else
-
     printf "It appears that Nginx is not running.\n(from pidfile: $nginx_pid)\nStarting Nginx.\n"
-
   fi
-
 }
 
-check() {
-
-  nginx -t -c "$nginx_conf"
-
-  local result=$?
-
-  if [[ $result -gt 0 ]] ; then
-
-    printf "\n$nginx_conf syntax NOT OK\n"
-
+nginx_check()
+{
+  if nginx -t -c "$nginx_conf" ; then
+    succeed "$nginx_conf syntax is OK"
   else
-
-    printf "\n$nginx_conf syntax OK\n"
-
+    fail "$nginx_conf syntax is NOT OK"
   fi
-
-  return $result
 }
 
-declare -i master_pid
+nginx_status()
+{
+  log "
+Nginx:
+  version: $("${nginx}" -V | head -1 | awk -F'\/' '{print $2}')"
 
-if [[ -f "$nginx_pid" ]] ;then
-  master_pid=$(cat "$nginx_pid")
-else
-  master_pid=0
-fi
+  if [[ -s "${nginx_pid}" ]] ; then
+    log "  status: running"
+    log "  pid: $(cat ${nginx_pid})"
+  else
+    log "  status: not running."
+  fi
+
+  log "  pidfile: ${nginx_pid}
+  error_log: $(awk '/^error_log/{print $2}' ${nginx_conf})
+  access_log: $(awk '/^access_log/{print $2}' ${nginx_conf})
+  dbfile: $(awk '/^dbfilename/{print $2}' ${nginx_conf})
+"
+}
+
+action="${1:-""}"
+
+parse_args
+
+initialize
 
 case "$action" in
-  start)    start   ;;
-  stop)     stop    ;;
-  restart)  restart ;;
-  reload)   reload  ;;
-  check)    check   ;;
-  log)      log     ;;
-  shutdown) shutdown ;;
-  help)     usage   ;;
+  start)    nginx_start    ;;
+  stop)     nginx_stop     ;;
+  restart)  nginx_restart  ;;
+  reload)   nginx_reload   ;;
+  check)    nginx_check    ;;
+  status)   nginx_status   ;;
+  log)      nginx_log      ;;
+  shutdown) nginx_shutdown ;;
+  help)     usage    ;;
   *)        usage ; exit 1 ;;
 esac
 
