Do not allow remove paths to trigger the revert.

diff --git a/deploy/modules/shell/dsl b/deploy/modules/shell/dsl
--- a/deploy/modules/shell/dsl
+++ b/deploy/modules/shell/dsl
@@ -213,7 +213,10 @@ cleanup()
 
     if array_is_nonempty old_releases
     then
-      remove_paths "${old_releases[@]}"
+      if ! remove_paths "${old_releases[@]}"
+      then
+        log "There was an error removing the old releases."
+      fi
     fi
   fi
 }
