Enhanced Rails extension.

diff --git a/rails/bin/bootstrap b/rails/bin/bootstrap
--- a/rails/bin/bootstrap
+++ b/rails/bin/bootstrap
@@ -2,18 +2,36 @@
 
 enter "${release_path}"
 
-file_is_nonempty *.gems && rvm gemset import *.gems
+if file_is_nonempty *.gems &&
+  command_exists "rvm"
+then
+  rvm gemset import *.gems
+fi
 
-if file_is_nonempty "Gemfile" ; then
-  command_exists bundle || install_gems bundler
-elif file_contains "config/environment.rb" "config.gem" ; then
+if file_is_nonempty "Gemfile"
+then
+  if ! command_exists bundle
+  then
+    install_gems bundler
+  fi
+elif file_contains "config/environment.rb" "config.gem"
+then
   rake gems:install
 else
   log "No Gemfile or config.gem entries detected, skipping gems."
 fi
 
-command_exists rake || install_gems rake
+if ! command_exists rake
+then
+  install_gems rake 0.8.7
+fi
 
-rake db:create
-rake db:migrate
+if command_exists rake
+then
+  rake db:create
+  rake db:migrate
+else
+  warn "'rake' command is missing, "\
+    "skipping db:create and db:migrate tasks."
+fi
 
